config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "homes#top"

  resources :users, only: [:show, :edit, :update, :index, :create] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'search' => "users#search", as: 'search'
  end
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :chats, only: [:show, :create, :destroy]
  resources :groups, only: [:new, :create, :index, :show, :edit, :update]
  resources :group_users, only: [:create, :destroy]
  resources :event_infos, only: [:create]

  get "search" => "searches#search"

  get 'home/about' => 'homes#about', as: 'about'
  patch 'users/:id' => 'users#update', as: 'update_user'

  get 'event_infos/:id/new'=> 'event_infos#new', as: 'new_event_info'
  # get 'event_infos/complete' => 'event_infos#complete', as: 'event_infos_complete'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users
  has_many :event_infos, dependent: :destroy
  belongs_to :owner, class_name: "User"

  validates :name, presence: true
  validates :introduction, presence: true

  has_one_attached :group_image

  def get_group_image(width, height)
    unless group_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      group_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    group_image.variant(resize_to_limit: [width, height]).processed
  end

  def join_to(group)
    @group_user = GroupUser.new
    @group_user.user_id = current_user.id
    @group_user.group_id = group.id
    @group_user.save
  end

  def delete_from(group)
    group_user = GroupUser.find_by(user_id: current_user, group_id: group.id)
    group_user.destroy
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    if @group.save
      flash[:notice] = "You have created the group successfully."
      redirect_to groups_path
    else
      render :new
    end
  end

  def index
    @groups = Group.all
    @book = Book.new
    @user = current_user
  end

  def show
    @group = Group.find(params[:id])
    @book = Book.new
    @user = current_user
    @group_users = @group.users
  end

  def edit
    @group = Group.find(params[:id])
    unless @group.owner_id == current_user.id
      redirect_to groups_path
    end
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      flash[:notice] = "You have updated the group successfully."
      redirect_to groups_path
    else
      render :edit
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :introduction, :group_image)
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Editting Group</h2>
      <% if @group.errors.any? %>
        <div id="error_explanation">
          <h3>
            <%= @group.errors.count %> errors prohibited this obj from being saved:
          </h3>
          <ul>
            <% @group.errors.full_messages.each do |message| %>
              <li>
                <%= message %>
              </li>
              <% end %>
          </ul>
        </div>
      <% end %>
      <%= form_with model: @group do |f| %>
        <div class="from-group">
          <label>グループ名</label>
          <%= f.text_field :name, class:"form-control" %>
        </div>
        <div class="from-group">
          <label>紹介文</label>
          <%= f.text_area :introduction, class:"form-control" %>
        </div>
        <div class="from-group">
          <label>グループ画像</label>
          <%= f.file_field :group_image, accept: "image/*", class:"form-control-file" %>
        </div>
        <div class="from-group" style="margin-top:20px;">
          <%= f.submit 'Update Group', url: 'group_path(@group.id)', method: :patch, class:"btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h3>
        <%= @book.errors.count %> errors prohibited this obj from being saved:
      </h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
          <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-3 border-right border-success">
      <%= render 'layouts/userinfo' , user: @user %>
      <%= render 'layouts/bookform' , book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Groups</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th>メンバー数</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @groups.each do |group| %>
            <tr>
              <td>
                <%= image_tag group.get_group_image(80,80) %>
              </td>
              <td>
                <%= link_to group_path(group.id) do %>
                  <%= group.name %>
                <% end %>
              </td>
              <td>
                <%= group.introduction %>
              </td>
              <td>
                <%= GroupUser.where(group_id: group.id).count %>
              </td>
              <td>
                <% if group.owner_id == current_user.id %>
                  <%= link_to "Edit", edit_group_path(group.id), class: "btn btn-success" %>
                <% end %>
              </td>
            </tr>
            <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Create Group</h2>
      <% if @group.errors.any? %>
        <div id="error_explanation">
          <h3>
            <%= @group.errors.count %> errors prohibited this obj from being saved:
          </h3>
          <ul>
            <% @group.errors.full_messages.each do |message| %>
              <li>
                <%= message %>
              </li>
              <% end %>
          </ul>
        </div>
      <% end %>
      <%= form_with model: @group do |f| %>
        <div class="from-group">
          <label>グループ名</label>
          <%= f.text_field :name, class:"form-control" %>
        </div>
        <div class="from-group">
          <label>紹介文</label>
          <%= f.text_area :introduction, class:"form-control" %>
        </div>
        <div class="from-group">
          <label>グループ画像</label>
          <%= f.file_field :group_image, accept: "image/*", class:"form-control-file" %>
        </div>
        <div class="from-group" style="margin-top:20px;">
          <%= f.submit 'Create Group', class:"btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h3>
        <%= @book.errors.count %> errors prohibited this obj from being saved:
      </h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
          <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-3 border-right border-success">
      <%= render 'layouts/userinfo' , user: @user %>
      <%= render 'layouts/bookform' , book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Group Detail</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th>メンバー</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <%= image_tag @group.get_group_image(80,80) %>
            </td>
            <td>
              <%= @group.name %>
            </td>
            <td>
              <%= @group.introduction %>
            </td>
            <td>
              <% @group_users.each do |group_user| %>
                <%= group_user.name %><br>
              <% end %>
            </td>
            <% if @group.owner_id == current_user.id %>
              <td>
                <%= link_to "Edit", edit_group_path(@group.id), class: "btn btn-success" %>
              </td>
              <td>
                <%= link_to "Notice an Event", new_event_info_path(@group.id), class: "btn btn-success" %>
              </td>
            <% end %>
            <td>
              <% if GroupUser.find_by(user_id: current_user, group_id: @group.id) == nil %>
                <%= link_to "Join this group", group_users_path(group_id: @group.id), method: :create, class: 'btn btn-sm btn-success'%>
              <% else %>
                <%= link_to "Leave this group", group_user_path(@group), method: :delete, class: 'btn btn-sm btn-danger' %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>