config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "homes#top"

  resources :users, only: [:show, :edit, :update, :index, :create] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'search' => "users#search", as: 'search'
  end
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :chats, only: [:show, :create, :destroy]
  resources :groups, only: [:new, :create, :index, :show, :edit, :update]
  resources :group_users, only: [:create, :destroy]
  resources :event_infos, only: [:create]

  get "search" => "searches#search"

  get 'home/about' => 'homes#about', as: 'about'
  patch 'users/:id' => 'users#update', as: 'update_user'

  get 'event_infos/:id/new'=> 'event_infos#new', as: 'new_event_info'
  # get 'event_infos/complete' => 'event_infos#complete', as: 'event_infos_complete'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :followings, through: :relationships, source: :followed #フォローしている人をたくさん持っている. followed_idとして保存されている？
  has_many :followers, through: :reverse_relationships, source: :follower #フォロワーをたくさん持っている． follower_idとして保存されている

  # DM機能
  has_many :chats, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
  has_many :rooms, through: :user_rooms

  has_many :view_counts, dependent: :destroy

  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  #フォローしたときの処理
  def follow(user_id)
    relationships.new(followed_id: user_id) # user_idの持ち主にフォローされたという関係性を作る

  end

  #フォローを外したときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy # user_idの持ち主にフォローされた人を探して消す
  end

  #フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?", "#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?", "%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?", "%#{word}%")
    else
      @user = User.all
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @book = Book.new
    # .post_imagesで特定のユーザの投稿すべてを持ってこれる
    # .allはユーザ関係なく全部
    @books = @user.books
  end

  def index
    @user = User.find(current_user.id)
    @users = User.all
    @book = Book.new
  end

  def edit
    user_id = params[:id].to_i
    unless user_id == current_user.id
      redirect_to user_path(current_user.id)
    end
    @user = User.find(current_user.id)
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def search
    @date = params[:date]
    @user = User.find(params[:user_id])
    @bookscount = @user.books.where(['created_at LIKE ? ', "#{@date}%"]).count
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_search.html.erb
<% if user_signed_in? %>
  <div class="search_form" style="margin-top:40px;">
    <%= form_with url: user_search_path(user_id), local: false, method: :get do |f| %>
      <%= f.date_field :date %>
      <%= f.submit "検索", class: "btn btn-outline-primary" %>
    <% end %>
  </div>
  <% unless bookscount.nil? %>
    <h4>検索結果</h4>
    <%= bookscount %>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h3>
            <%= @user.errors.count %> errors prohibited this obj from being saved:
          </h3>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
        <%= form_with model: @user do |f| %>
          <div class="form-group">
            <label for="user_name">Name</label>
            <%= f.text_field :name, class:"form-control" %>
          </div>
          <div class="form-group">
            <label for="user_image">Image</label>
            <%= f.file_field :profile_image, accept: "image/*", class: "form-control-file" %>
          </div>
          <div class="form-group">
            <label for="user_introduction">Introduction</label>
            <%= f.text_area :introduction, class:"form-control" %>
          </div>
          <div class="form-group">
            <%= f.submit 'Update User', url: 'user_path(current_user.id)', method: :patch, class:"btn btn-success" %>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h3>
        <%= @book.errors.count %> errors prohibited this obj from being saved:
      </h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-3 border-right border-success">
      <%= render 'layouts/userinfo', user: @user %>
      <%= render 'layouts/bookform', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <% if user_signed_in? %>
        <div class="search_form float-right">
          <%= form_with url: search_path, local: true, method: :get do |f| %>
            <%= f.text_field :word %>
            <%= f.select :range, options_for_select([['User'], ['Book']]) %>
            <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
            <%= f.submit "検索", class: "btn btn-primary" %>
          <% end %>
        </div>
      <% end %>
      <h2>Users</h2>
      <%= link_to "グループを作成する", new_group_path %> | <%= link_to "グループ一覧", groups_path %>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= image_tag user.get_profile_image(80,80) %>
              </td>
              <td>
                <%= user.name %>
              </td>
              <td>
                フォロー数:<%= user.followings.count %>
              </td>
              <td>
                フォロワー数:<%= user.followers.count %>
              </td>

              <td>
                <% unless user == current_user %>
                  <% if current_user.following?(user) %>
                    <%= link_to "フォロー解除", user_relationships_path(user.id), method: :delete %>
                  <% else %>
                    <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
                  <% end %>
                <% end %>
              </td>
              <td>
                <%= link_to "Show", user_path(user.id) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/search.js.erb
 $(".search").html("<%= j(render 'users/search', bookscount: @bookscount, user_id: @user.id) %>");

app/views/users/show.html.erb
<p id="notice">
  <%= flash[:notice] %>
</p>
<div class="container px-5 px-sm-0">
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h3>
        <%= @book.errors.count %> errors prohibited this obj from being saved:
      </h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-3 border-right border-success">
      <%= render 'layouts/userinfo', user: @user %>
      <%= render 'layouts/bookform', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <% if user_signed_in? %>
        <div class="search_form float-right">
          <%= form_with url: search_path, local: true, method: :get do |f| %>
            <%= f.text_field :word %>
            <%= f.select :range, options_for_select([['User'], ['Book']]) %>
            <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
            <%= f.submit "検索", class: "btn btn-primary" %>
          <% end %>
        </div>
      <% end %>
      <h2>Books</h2>
      <table class="table table-hover table-inverse" style="margin-bottom:40px;">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user.id) do %>
                  <%= image_tag book.user.get_profile_image(80,80) %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book.id) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td>
                <%= book.body %>
              </td>
              <td>
                <% if book.favorited_by?(current_user)  %>
                  <%= link_to book_favorites_path(book.id), method: :delete do %>
                    <i class="fas fa-heart"></i><%= book.favorites.count %>
                  <% end %>
                <% else %>
                  <%= link_to book_favorites_path(book.id), method: :post do %>
                    <i class="far fa-heart"></i><%= book.favorites.count %>
                  <% end %>
                <% end %>
              </td>
              <td>
              コメント数:<%= book.book_comments.count %>
            </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <h4>７日分の投稿数</h4>
      <table class="table table-hover table-inverse border border-success" style="width:80%;margin:30px auto 0;text-align:center;">
        <thead>
          <th>６日前</th>
          <th>５日前</th>
          <th>４日前</th>
          <th>３日前</th>
          <th>２日前</th>
          <th>１日前</th>
          <th>今日</th>
        </thead>
        <tbody>
          <tr>
            <td>
              <%= @books.where(created_at: 6.day.ago.all_day).count %>
            </td>
            <td>
              <%= @books.where(created_at: 5.day.ago.all_day).count %>
            </td>
            <td>
              <%= @books.where(created_at: 4.day.ago.all_day).count %>
            </td>
            <td>
              <%= @books.where(created_at: 3.day.ago.all_day).count %>
            </td>
            <td>
              <%= @books.where(created_at: 2.day.ago.all_day).count %>
            </td>
            <td>
              <%= @books.created_yesterday.count %>
            </td>
            <td>
              <%= @books.created_today.count %>
            </td>
          </tr>
        </tbody>
      </table>
      <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
      <canvas id="lineChart" style="margin:20px 60px 40px;"></canvas>
      <script>
        let lineCtx = document.getElementById("lineChart");
        // 線グラフの設定
        let lineConfig = {
          type: 'line',
          data: {
            // ※labelとデータの関係は得にありません
            labels: ['６日前', '５日前', '４日前', '３日前', '２日前', '１日前', '今日'],
            datasets: [{
              label: '投稿した本の数',
              data: [ <%= @books.where(created_at: 6.day.ago.all_day).count %>, <%= @books.where(created_at: 5.day.ago.all_day).count %>, <%= @books.where(created_at: 4.day.ago.all_day).count %>, <%= @books.where(created_at: 3.day.ago.all_day).count %>, <%= @books.where(created_at: 2.day.ago.all_day).count %>, <%= @books.created_yesterday.count %>, <%= @books.created_today.count %>],
              borderColor: '#484',
              tension: 0.5,
            }],
          },
          options: {
            plugins: {
              title: {
                display: true,
                text: '７日間の投稿数の比較',
              }
            },
            scales: {
              // Y軸の最大値・最小値、目盛りの範囲などを設定する
              y: {
                suggestedMin: 0,
                suggestedMax: 10,
                ticks: {
                  stepSize: 1,
                }
              }
            },
          },
        };
        let lineChart = new Chart(lineCtx, lineConfig);
      </script>
      <%# <script>
        const config = document.getElementById('myChart');

        new Chart(config, {
          type: 'line',
          data: {
            labels: ['６日前', '５日前', '４日前', '３日前', '２日前', '１日前', '今日'],
            datasets: [{
              label: '# of Votes',
              data: [@books.where(created_at: 6.day.ago.all_day).count, @books.where(created_at: 5.day.ago.all_day).count, @books.where(created_at: 4.day.ago.all_day).count, @books.where(created_at: 3.day.ago.all_day).count, @books.where(created_at: 2.day.ago.all_day).count, @books.where(created_at: 1.day.ago.all_day).count, @books.where(created_at: Time.current.all_day).count],
              borderWidth: 1
            }]
          },
          options: {
            scales: {
              y: {
                beginAtZero: true
              }
            }
          }
        });
      </script> %>
      <h4>投稿数の前日比・前週比</h4>
      <table class="table table-hover table-inverse border border-success" style="width:80%;margin:30px auto 0;text-align:center;">
        <thead>
          <th>今日の投稿数</th>
          <th>前日の投稿数</th>
          <th>前日比</th>
        </thead>
        <tbody>
          <tr>
            <td>
              <%= @books.created_today.count %>
            </td>
            <td>
              <%= @books.created_yesterday.count %>
            </td>
            <td>
              <% if @books.created_yesterday.count == 0 %>
                -
              <% else %>
                <%= ((@books.created_today.count / @books.created_yesterday.count)*100).round %>%
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
      <table class="table table-hover table-inverse border border-success" style="width:80%;margin:10px auto 0;text-align:center;">
        <thead>
          <th>今週の投稿数</th>
          <th>先週の投稿数</th>
          <th>前週比</th>
        </thead>
        <tbody>
          <tr>
            <td>
              <%= @books.created_this_week.count %>
            </td>
            <td>
              <%= @books.created_last_week.count %>
            </td>
            <td>
              <% if @books.created_last_week.count == 0 %>
                -
              <% else %>
                <%= ((@books.created_this_week.count / @books.created_last_week.count)*100).round %>%
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
      <div class="search">
        <%= render 'search', user_id: @user.id, bookscount: nil %>
      </div>
    </div>
  </div>
</div>