config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "homes#top"

  resources :users, only: [:show, :edit, :update, :index, :create] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'search' => "users#search", as: 'search'
  end
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :chats, only: [:show, :create, :destroy]
  resources :groups, only: [:new, :create, :index, :show, :edit, :update]
  resources :group_users, only: [:create, :destroy]
  resources :event_infos, only: [:create]

  get "search" => "searches#search"

  get 'home/about' => 'homes#about', as: 'about'
  patch 'users/:id' => 'users#update', as: 'update_user'

  get 'event_infos/:id/new'=> 'event_infos#new', as: 'new_event_info'
  # get 'event_infos/complete' => 'event_infos#complete', as: 'event_infos_complete'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # いいねの多い順に表示
  # ラムダ｛｝の中に条件を提示
    # create_atカラムが1.week.ago.beginning_of_day（一週間前）からTime.current.end_of_day（今日）までに該当するものを指定
  has_many :week_favorites, -> { where(created_at: 1.week.ago.beginning_of_day..Time.current.end_of_day) }

  # 閲覧数
  has_many :view_counts, dependent: :destroy

  # 本の投稿数
  scope :created_today, -> {where(created_at: Time.current.all_day)}
  scope :created_yesterday, -> {where(created_at: 1.day.ago.all_day)}
  scope :created_this_week, -> {where(created_at: (Time.current - 6.day).beginning_of_day..Time.current.end_of_day)}
  scope :created_last_week, -> {where(created_at: (Time.current - 13.day).beginning_of_day..(Time.current - 7.day).end_of_day)}

  validates :title, presence: true
  validates :body, presence: true

  validates :body,
    length: { maximum: 200 }

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?", "#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?", "#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?", "%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?", "%#{word}%")
    else
      @book = Book.all
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created the book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = User.find(current_user.id)
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    unless @book.user_id == current_user.id
      redirect_to books_path
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated the book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def index
    @user = User.find(current_user.id)
    @book = Book.new

    # sortを使って並べ替え
    # .sortは-1が来たら要素を逆転させる．
    # b <=> a は, b < aの時に-1, b > aの時に1, b = aの時に0を返す．
    to  = Time.current.at_end_of_day
    from  = (to - 6.day).at_beginning_of_day
    @books = Book.all.sort {|a,b|
      b.favorites.where(created_at: from...to).size <=>
      a.favorites.where(created_at: from...to).size
    }
  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @book_comments = @book.book_comments
    @book_comment = BookComment.new
    # if ViewCount.find_by(user_id: current_user.id, book_id: @book.id).nil?
      view_count = current_user.view_counts.create(book_id: @book.id)
      view_count.save
    # end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Editing Book</h2>
      <% if @book.errors.any? %>
        <div id="error_explanation">
          <h3>
            <%= @book.errors.count %> errors prohibited this obj from being saved:
          </h3>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
        <%= form_with model: @book do |f| %>
          <div class="form-group">
            <label for="book_title">Title</label>
            <%= f.text_field :title, class:"form-control book_title" %>
          </div>
          <div class="form-group">
            <label for="book_opinion">Opinion</label>
            <%= f.text_area :body, class: "form-control-file book_body" %>
          </div>
          <div class="form-group">
            <%= f.submit 'Update Book', class:"btn btn-success" %>
          </div>
        <% end %>
        <%= link_to "Show", book_path(@book.id) %>
        |
        <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">

  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h3>
        <%= @book.errors.count %> errors prohibited this obj from being saved:
      </h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-3 border-right border-success">
      <%= render 'layouts/userinfo', user: @user %>
      <%= render 'layouts/bookform', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <% if user_signed_in? %>
        <div class="search_form float-right">
          <%= form_with url: search_path, local: true, method: :get do |f| %>
            <%= f.text_field :word %>
            <%= f.select :range, options_for_select([['User'], ['Book']]) %>
            <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
            <%= f.submit "検索", class: "btn btn-primary" %>
          <% end %>
        </div>
      <% end %>
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user.id) do %>
                  <%= image_tag book.user.get_profile_image(80,80) %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book.id) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td>
                <%= book.body %>
              </td>
              <td  id="favorite_buttons_<%= book.id %>">
                <%= render "favorites/favorite-btn", book: book %>
              </td>
              <td>
                コメント数:<%= book.book_comments.count %>
              </td>
              <td>
                閲覧数:<%= book.view_counts.count %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<p id="notice">
  <%= flash[:notice] %>
</p>
<div class="container px-5 px-sm-0">
  <% if @book_new.errors.any? %>
    <div id="error_explanation">
      <h3>
        <%= @book_new.errors.count %> errors prohibited this obj from being saved:
      </h3>
      <ul>
        <% @book_new.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-3 border-right border-success">
      <%= render 'layouts/userinfo', user: @book.user %>
      <%= render 'layouts/bookform', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <% if user_signed_in? %>
        <div class="search_form float-right">
          <%= form_with url: search_path, local: true, method: :get do |f| %>
            <%= f.text_field :word %>
            <%= f.select :range, options_for_select([['User'], ['Book']]) %>
            <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
            <%= f.submit "検索", class: "btn btn-primary" %>
          <% end %>
        </div>
      <% end %>
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@book.user.id) do %>
                <%= image_tag @book.user.get_profile_image(100,100) %><br>
                <%= @book.user.name %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(@book.id) do  %>
                <%= @book.title %>
              <% end %>
            </td>
            <td><%= @book.body %></td>
            <td class="favorite-btn">
              <%= render "favorites/favorite-btn", book: @book %>
            </td>
            <td>
              コメント数:<%= @book.book_comments.count %>
            </td>
            <td>
              閲覧数:<%= @book.view_counts.count %>
            </td>
            <% if @book.user == current_user %>
              <td>
                  <%= link_to "Edit", edit_book_path(@book.id), class: 'btn btn-sm btn-success' %>
              </td>
              <td>
                <%= link_to "Destroy", book_path, method: :delete, class: 'btn btn-sm btn-danger' %>
              </td>
            <% end %>
          </tr>
        </tbody>
      </table>
      <div class="comments-index">
        <%= render 'book_comments/index', book_comments: @book_comments, book: @book %>
      </div>
    </div>
  </div>
</div>