config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "homes#top"

  resources :users, only: [:show, :edit, :update, :index, :create] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'search' => "users#search", as: 'search'
  end
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :chats, only: [:show, :create, :destroy]
  resources :groups, only: [:new, :create, :index, :show, :edit, :update]
  resources :group_users, only: [:create, :destroy]
  resources :event_infos, only: [:create]

  get "search" => "searches#search"

  get 'home/about' => 'homes#about', as: 'about'
  patch 'users/:id' => 'users#update', as: 'update_user'

  get 'event_infos/:id/new'=> 'event_infos#new', as: 'new_event_info'
  # get 'event_infos/complete' => 'event_infos#complete', as: 'event_infos_complete'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # いいねの多い順に表示
  # ラムダ｛｝の中に条件を提示
    # create_atカラムが1.week.ago.beginning_of_day（一週間前）からTime.current.end_of_day（今日）までに該当するものを指定
  has_many :week_favorites, -> { where(created_at: 1.week.ago.beginning_of_day..Time.current.end_of_day) }

  # 閲覧数
  has_many :view_counts, dependent: :destroy

  # 本の投稿数
  scope :created_today, -> {where(created_at: Time.current.all_day)}
  scope :created_yesterday, -> {where(created_at: 1.day.ago.all_day)}
  scope :created_this_week, -> {where(created_at: (Time.current - 6.day).beginning_of_day..Time.current.end_of_day)}
  scope :created_last_week, -> {where(created_at: (Time.current - 13.day).beginning_of_day..(Time.current - 7.day).end_of_day)}

  validates :title, presence: true
  validates :body, presence: true

  validates :body,
    length: { maximum: 200 }

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?", "#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?", "#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?", "%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?", "%#{word}%")
    else
      @book = Book.all
    end
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
  
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: {maximum: 140}
end

app/models/event_info.rb
class EventInfo < ApplicationRecord
  belongs_to :group
  validates :title, presence: true
  validates :content, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
  validates :user_id, uniqueness: { scope: :book_id} 
  #1つの投稿に対してしかいいねできない
  
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users
  has_many :event_infos, dependent: :destroy
  belongs_to :owner, class_name: "User"

  validates :name, presence: true
  validates :introduction, presence: true

  has_one_attached :group_image

  def get_group_image(width, height)
    unless group_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      group_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    group_image.variant(resize_to_limit: [width, height]).processed
  end

  def join_to(group)
    @group_user = GroupUser.new
    @group_user.user_id = current_user.id
    @group_user.group_id = group.id
    @group_user.save
  end

  def delete_from(group)
    group_user = GroupUser.find_by(user_id: current_user, group_id: group.id)
    group_user.destroy
  end

end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  # follower_idとかfollowed_idとか言ってるけど中身はuserのことだよって意味
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :chats, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
  has_many :users, through: :user_rooms
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :followings, through: :relationships, source: :followed #フォローしている人をたくさん持っている. followed_idとして保存されている？
  has_many :followers, through: :reverse_relationships, source: :follower #フォロワーをたくさん持っている． follower_idとして保存されている

  # DM機能
  has_many :chats, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
  has_many :rooms, through: :user_rooms

  has_many :view_counts, dependent: :destroy

  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  #フォローしたときの処理
  def follow(user_id)
    relationships.new(followed_id: user_id) # user_idの持ち主にフォローされたという関係性を作る

  end

  #フォローを外したときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy # user_idの持ち主にフォローされた人を探して消す
  end

  #フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?", "#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?", "%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?", "%#{word}%")
    else
      @user = User.all
    end
  end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/view_count.rb
class ViewCount < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_bookform.html.erb
<h2 class="mt-3">New book</h2>
  <%= form_with model: book do |f| %>
    <div class="form-group">
      <label>Title</label>
      <%= f.text_field :title, class:"form-control" %>
    </div>
    <div class="form-group">
      <label>Opinion</label>
      <%= f.text_area :body, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit 'Create Book', class:"btn btn-success float-right" %>
    </div>
  <% end %>

app/views/layouts/_userinfo.html.erb
<h2>User info</h2>
<%= image_tag user.get_profile_image(100,100) %>
<% if current_user.following?(user) && user.following?(current_user) %>
  <%= link_to "DMへ", chat_path(user), class:"btn btn-outline-success float-right" %>
<% end %>
<table class="table" style="margin-top:10px;">
  <tbody>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
    <tr>
      <th>follows</th>
      <th>
        <%= link_to user_followings_path(user) do %>
          <%= user.followings.count %>
        <% end %>
      </th>
    </tr>
    <tr>
      <th>followers</th>
      <th>
        <%= link_to user_followers_path(user) do %>
          <%= user.followers.count %>
        <% end %>
      </th>
    </tr>
  </tbody>
</table>
<% unless user == current_user %>
  <% if current_user.following?(user) %>
    <%= link_to "フォロー解除", user_relationships_path(user.id), method: :delete %>
  <% else %>
    <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
  <% end %>
<% end %>
<div class="row" style='margin: 10px 5px 0px 5px;'>
  <%= link_to edit_user_path(current_user), class: "btn btn-outline-secondary btn-block edit_user_path" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>
<div class="adaptable-bottom"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="fontawesome-i2svg-active fontawesome-i2svg-complete">
  <head>
    <title>Bookers2</title>
    <!--<meta name="csrf-param" content="authenticity_token">-->
    <!--<meta name="csrf-token" content="ZRNkHCaOfQxlHRm4TBYkF7bQEtVOJ2GU6BBM7IU2-MtIANwtyzOEFda26PtOxrtos7TTWLz0DdxkOFU6JFUF5w">-->
    <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_link_tag 'application', media: 'all' %>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.1/chart.min.js" integrity="sha512-L0Shl7nXXzIlBSUUPpxrokqq4ojqgZFQczTYlGjzONGTDAcLremjwaWv5A+EDLnxhQzY5xUZPWLOLqYRkY0Cbw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container">
          <a class="navbar-brand" href="/" style="color:#0d4103;">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
                <i class="fas fa-home"></i>
                Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to users_path, class: 'nav-link text-light' do %>
                <i class="fas fa-users"></i>
                Users
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to books_path, class: 'nav-link text-light' do %>
                <i class="fas fa-book-open"></i>
                Books
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                <i class="fas fa-sign-out-alt"></i>
                Log out
              <% end %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to root_path, class: 'nav-link text-light' do %>
                <i class="fas fa-home"></i>
                Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to about_path, class: 'nav-link text-light' do %>
                <i class="fas fa-link"></i>
                About
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                <i class="fas fa-user-plus"></i>
                Sign up
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
                <i class="fas fa-sign-in-alt"></i>
                Log in
              <% end %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
    <%= yield %>
    </main>
    <footer>
      <%# <div class="footer-margin"></div> %>
      <div class="container mt-2 correct-footer">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Insratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>